language: node_js
node_js:
  - "4.8"
  - "6.10"
  - "7.10"
  - "8.0"
sudo: false
env:
  - CC=gcc-6 CXX=g++-6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
